baseurl: /uni-notes
title: Uni-notes
subtitle: Lecture notes for Unimi.
author: Edoardo Federici
simple_search: http://google.com/search
description: Lecture notes for Unimi.
name: cs228-notes
markdown_ext: "markdown,mkdown,mkdn,mkd,md"
permalink: /articles/:short_year/:title
timezone: Europe
excerpt_separator: <!--more-->  # you can specify your own separator, of course.
exclude: ['Gemfile', 'Gemfile.lock', 'Rakefile', 'README.md']
post:
  template: _post.txt
  extension: md
page:
  template: _page.txt
  extension: md
editor: gvim
git:
  branch: master
transfer:
  command: rsync
  settings: -av
  source: _site/
